### PR TITLE
Fix-#5

### PR DESCRIPTION
**Pull request by amreshk005**
@vibhoothiiaanand I have added the Question Model as per required, take a look over it.

### CODE REVIEW

**Comment by harshithpabbati** [comment]
@amreshk005 can you align in the following way
1. Author (1st Line)
2.  Minimum Mark, Maximum Mark , Difficulty and Date (2nd Line)
3.  Type (3rd Line)
4. Rich TextFeild (4th Line)

**Comment by amreshk005** [comment]
@harshithpabbati I have aligned the fields according to you.

**Comment by harshithpabbati** [comment]
@amreshk005 Well It looks good. Can you please squash the commits.

**Comment by amreshk005** [comment]
@harshithpabbati I have squashed the commits.

Please take a look.

**Review by harshithpabbati — APPROVED** [review]
Thanks! For your contribution @amreshk005

**Pull request merged**
