### PR TITLE
Solved issue #15

### PR DESCRIPTION
**Pull request by nipan09**
Fixes #17

### CODE REVIEW

**Review by vibhoothi — CHANGES_REQUESTED** [review]
Hi,
Please rebase and send PR again
`git rebase -i origin/master`

Nit: Please use better commit message 

Refer to [This](https://chris.beams.io/posts/git-commit/) for better idea


Best,
VIbhoothi

**Comment by vchrombie** [comment]
Please edit the description too. It is good to have a description for a PR.

**Comment by vibhoothiiaanand** [comment]
Please Squash as one commit and use proper commit message

**Review by vibhoothi — CHANGES_REQUESTED** [review]
Do the following:
- [ ] Use Proper Commit Message
- [x] Squash and push the changes 
- [x] Update Description 
- [x] Rebase if needed 
- [x] Make sure no other changes are in this PR

**Comment by vchrombie** [comment]
@nipan09 
Please add "Fixes #17" to your description so that the merge the respective issue automatically.

**Pull request closed without merging**
